Update Cloudflare Workers deploy action to dynamically create and reference D1 database IDs. Simplify `wrangler.toml` generation logic.

diff --git a/.github/workflows/deploy/cloudflare_workers/action.yml b/.github/workflows/deploy/cloudflare_workers/action.yml
--- a/.github/workflows/deploy/cloudflare_workers/action.yml
+++ b/.github/workflows/deploy/cloudflare_workers/action.yml
@@ -97,10 +97,6 @@ runs:
       working-directory: ${{ inputs.working_dir }}
       run: mv dist crates/cloudflare_workers/public
 
-    - shell: bash
-      working-directory: ${{ inputs.working_dir }}
-      run: PROJECT_NAME="${{ inputs.project_name }}" SITE_URL="${{ inputs.site_url }}" envsubst < crates/cloudflare_workers/wrangler.template.toml > crates/cloudflare_workers/wrangler.toml
-
     - uses: dtolnay/rust-toolchain@stable
       with:
         targets: wasm32-unknown-unknown
@@ -111,4 +107,18 @@ runs:
         workingDirectory: ${{ inputs.working_dir }}/crates/cloudflare_workers
         accountId: ${{ inputs.cloudflare_account_id }}
         apiToken: ${{ inputs.cloudflare_api_token }}
+        preCommands: |
+          DB_NAME="${{ inputs.project_name }}-blog-db"
+          DATABASE_ID=$wrangler d1 list --json | jq -r '.[] | select(.name == "'"${DB_NAME}"'") | .uuid')
+          if [ -z "$DATABASE_ID" ]; then
+            echo "Create D1 Database '${DB_NAME}'"
+            wrangler d1 create "${DB_NAME}" --json
+            DATABASE_ID=$wrangler d1 list --json | jq -r '.[] | select(.name == "'"${DB_NAME}"'") | .uuid')
+          fi
+
+          if [ -z "$DATABASE_ID" ]; then
+            echo "ERROR: Cannot find D1 Database ${DB_NAME}"
+            exit 1
+          fi
+          PROJECT_NAME="${{ inputs.project_name }}" SITE_URL="${{ inputs.site_url }}" D1_DATABASE_ID=$DATABASE_ID envsubst < wrangler.template.toml > wrangler.toml
         command: deploy
