Refactor Cloudflare Workers deploy action to use `shell` script for D1 database setup, simplifying workflow structure.

diff --git a/.github/workflows/deploy/cloudflare_workers/action.yml b/.github/workflows/deploy/cloudflare_workers/action.yml
--- a/.github/workflows/deploy/cloudflare_workers/action.yml
+++ b/.github/workflows/deploy/cloudflare_workers/action.yml
@@ -101,27 +101,30 @@ runs:
       with:
         targets: wasm32-unknown-unknown
 
+    - shell: bash
+      working-directory: ${{ inputs.working_dir }}/crates/cloudflare_workers
+      run: |
+        export CLOUDFLARE_API_TOKEN="${{ inputs.cloudflare_api_token }}"
+        
+        DB_NAME="${{ inputs.project_name }}-blog-db"
+        wrangler d1 list --json
+        DATABASE_ID=$(wrangler d1 list --json | jq -r '.[] | select(.name == "${DB_NAME}") | .uuid')
+        if [ -z "$DATABASE_ID" ]; then
+          echo "Create D1 Database '${DB_NAME}'"
+          wrangler d1 create "${DB_NAME}" --json
+          DATABASE_ID=$(wrangler d1 list --json | jq -r '.[] | select(.name == "${DB_NAME}") | .uuid')
+        fi
+
+        if [ -z "$DATABASE_ID" ]; then
+          echo "ERROR: Cannot find D1 Database ${DB_NAME}"
+          exit 1
+        fi
+        PROJECT_NAME="${{ inputs.project_name }}" SITE_URL="${{ inputs.site_url }}" D1_DATABASE_ID=$DATABASE_ID envsubst < wrangler.template.toml > wrangler.toml
+
     - name: Deploy to Cloudflare Workers
       uses: cloudflare/wrangler-action@v3
       with:
         workingDirectory: ${{ inputs.working_dir }}/crates/cloudflare_workers
         accountId: ${{ inputs.cloudflare_account_id }}
         apiToken: ${{ inputs.cloudflare_api_token }}
-        preCommands: |
-          npm install -g wrangler
-          
-          DB_NAME="${{ inputs.project_name }}-blog-db"
-          wrangler d1 list --json
-          DATABASE_ID=$(wrangler d1 list --json | jq -r '.[] | select(.name == "${DB_NAME}") | .uuid')
-          if [ -z "$DATABASE_ID" ]; then
-            echo "Create D1 Database '${DB_NAME}'"
-            wrangler d1 create "${DB_NAME}" --json
-            DATABASE_ID=$(wrangler d1 list --json | jq -r '.[] | select(.name == "${DB_NAME}") | .uuid')
-          fi
-
-          if [ -z "$DATABASE_ID" ]; then
-            echo "ERROR: Cannot find D1 Database ${DB_NAME}"
-            exit 1
-          fi
-          PROJECT_NAME="${{ inputs.project_name }}" SITE_URL="${{ inputs.site_url }}" D1_DATABASE_ID=$DATABASE_ID envsubst < wrangler.template.toml > wrangler.toml
         command: deploy
